#ifndef _FRAGVIEW_OPTIONDICSET_H_
#define _FRAGVIEW_OPTIONDICSET_H_ 1

/*  */
#define CONFIG_RENDERER_DRIVER "render-driver"
#define CONFIG_RENDERINTERFACE_EXTENSION ""
#define CONFIG_RENDERINTERFACE_LAYERS ""
#define CONFIG_RENDERINTERFACE_OPENGL ""
#define CONFIG_RENDERINTERFACE_OPENGL_CORE ""
#define CONFIG_RENDERINTERFACE_VULKAN_VERSION ""
#define CONFIG_RENDERINTERFACE_DIRECTX_VERSION ""
#define CONFIG_RENDERINTERFACE_DEBUG ""
#define CONFIG_RENDERINTERFACE_DEBUG_TRACER ""
#define CONFIG_RENDERINTERFACE_ALPHA ""
#define CONFIG_RENDERINTERFACE_VSYNC ""
#define CONFIG_RENDERINTERFACE_GAMMA_CORRECTION ""
#define CONFIG_RENDERINTERFACE_USE_MSAA ""
#define CONFIG_RENDERINTERFACE_MSAA_SAMPLES ""
#define CONFIG_RENDRINTERFACE_VERSION ""

/*  */
#define CONFIG_RENDERWIDNOW_CONFIG "render-window-settings"
#define CONFIG_RENDERWINDOW_FULLSCREEN "fullscreen"
#define CONFIG_RENDERWINDOW_ISFULLSCREEN "isFullscreen"
#define CONFIG_RENDERWINDOW_SCREEN_WIDTH "screen-width"
#define CONFIG_RENDERWINDOW_SCREEN_HEIGHT "screen-height"
#define CONFIG_RENDERWINDOW_SCREEN_MAX_WIDTH "screen-max-width"
#define CONFIG_RENDERIWNDOW_SCREEN_MAX_HEIGHT "screen-max-height"
#define CONFIG_RENDERWINDOW_SCREEN_MIN_WIDTH "screen-min-width"
#define CONFIG_RENDERWINDOW_SCREEN_MIN_HEIGHT "screen-min-height"
#define CONFIG_RENDERWINDOW_SCREEN_X "screen-x"
#define CONFIG_RENDERWINDOW_SCREEN_Y "screen-y"
#define CONFIG_RENDERIWNDOW_RENDERINBACKGROUND "background-rendering"
#define CONFIG_RENDERWINDOW_RESIZABLE "window-resizable"
#define CONFIG_RENDERWINDOW_BORDERED "window-bordered"

/**/
#define CONFIG_CACHE_SHADER ""
#define CONFIG_DYNAMIC_RENDERINTERFACE ""
#define CONFIG_DEBUG ""

/**/
#define CONFIG_KONACHAN_SETTINGS ""

/**/
#define CONFIG_CACHE_SETTINGS ""
#define CONFIG_CACHE_DATA ""
#define CONFIG_USE_CACHE
#define CONFIG_CACHE_DIR

#define CONFIG_SCENE "default-scene-settings"

#endif
